

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:court